paddlecloud job train --cluster-name paddle-jpaas-ai00 \
--job-version custom-fluid \
--k8s-gpu-type baidu/gpu_p40 \
--k8s-gpu-cards 4 \
--k8s-priority high \
--k8s-wall-time 10:00:00 \
--k8s-memory 100Gi \
--k8s-ps-memory 20Gi \
--job-name s-transformer \
--start-cmd "python run.py" \
--job-conf transformer/common.py \
--files transformer/run.py transformer/common.py \
--image-addr "registry.baidu.com/qiuxuezhong/qiuxuezhong_fluid_test:latest"
