paddlecloud job train --cluster-name paddle-jpaas-ai00 \
--job-version custom-fluid \
--k8s-gpu-type baidu/gpu_p40 \
--k8s-gpu-cards 8 \
--k8s-priority high \
--k8s-memory 200Gi \
--k8s-ps-memory 20Gi \
--job-name m-transformer-shantou \
--start-cmd "python run_shantou.py" \
--job-conf transformer/common.py \
--files transformer/run_shantou.py transformer/common.py \
--k8s-not-local  \
--k8s-trainers 4 \
--k8s-ps-num 4 \
--k8s-ps-cores 1 \
--image-addr "registry.baidu.com/qiuxuezhong/fluid_gpu:0.14.0"
