paddlecloud job train \
--job-version custom-fluid \
--cluster-name yq01-jpaas-paddle01-cpu \
--k8s-priority high \
--k8s-wall-time 10:00:00 \
--k8s-memory 100Gi \
--k8s-ps-memory 20Gi \
--job-name m-cpu-transformer \
--start-cmd "python -u run_cpu.py" \
--job-conf transformer/common.py \
--files transformer/common.py transformer/run_cpu.py \
--k8s-not-local  \
--k8s-trainers 4 \
--k8s-ps-num 2 \
--k8s-ps-cores 1 \
--image-addr registry.baidu.com/qiuxuezhong/paddlepaddle-cpu:test
